export const localization = {
	documents: 'Documents',
	search: 'Search',
	newDocument: 'New Document',
	saved: 'Saved',
	preview: 'Preview',
	pdf: 'PDF',
	heading: 'Heading',
	bold: 'Bold',
	italic: 'Italic',
	blockquote: 'Blockquote',
	list: 'List',
	numberedList: 'Numbered List',
	code: 'Code',
	logout: 'Logout',
	deleteDialogTitle: 'Delete',
	deleteDialogMessage: 'Are you sure you want to delete {0}?',
	yesDelete: 'Yes, Delete',
	noDoNotDelete: "No, Don't Delete",
	save: 'Save',
	cancel: 'Cancel',
	documentName: 'Document Name',
	section: 'Section',
};
